db_name: "MCSSQueryStrategies"
table_name: "Test"
output_path: "results/"
closure_operators: ["sp"]
query_strategies: ["greedy", "greedy_random", "nn", "farthest"]
number_of_repetitions: 1
graph_sizes: [100]
graph_densities: [1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2]
class_start_sizes: [[1,1]]
